controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:

    left_wheel_names: ["Revolute 7"]
    right_wheel_names: ["Revolute 3"]

    wheel_separation: 0.1
    wheel_radius: 0.0325

    base_frame_id: base_footprint
    odom_frame_id: odom

    publish_rate: 50.0
    use_stamped_vel: false

    enable_odom_tf: true
    open_loop: false

    cmd_vel_timeout: 0.5

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    linear:
      x:
        has_velocity_limits: false

    angular:
      z:
        has_velocity_limits: false